(define (problem problemacarretera) (:domain carreteras)
(:objects
	cuadrilla1 cuadrilla2 cuadrilla3 cuadrilla4 - cuadrilla
	cisterna1 cisterna2 - cisterna
	pavimentadora1 pavimentadora2 - pavimentadora
	compactadora1 - compactadora
	tramo1 tramo2 tramo3 tramo4 tramo5 - tramo
)

(:init
	(camino tramo1 tramo2)
	(camino tramo2 tramo3)
    (camino tramo2 tramo4)
    (camino tramo3 tramo5)
    (camino tramo4 tramo5)
    (camino tramo2 tramo1)
	(camino tramo3 tramo2)
    (camino tramo4 tramo2)
    (camino tramo5 tramo3)
    (camino tramo5 tramo4)
    (at cuadrilla1 tramo1)
    (at cuadrilla2 tramo1)
    (at cuadrilla3 tramo5)
    (at cuadrilla4 tramo5)
    (at cisterna1 tramo1)
    (at cisterna2 tramo1)
    (at pavimentadora1 tramo2)
    (at pavimentadora2 tramo2)
    (at compactadora1 tramo5)
	(compactado tramo3)
    (compactado tramo4)
    (compactado tramo5)
    (disponible tramo1)
    (disponible tramo2)
    (disponible tramo3)
    (disponible tramo4)
    (disponible tramo5)
    (disponible cuadrilla1)
    (disponible cuadrilla2)
    (disponible cuadrilla3)
    (disponible cuadrilla4)
    (disponible pavimentadora1)
    (disponible pavimentadora2)
    (disponible cisterna1)
    (disponible cisterna2)
    (disponible compactadora1)
    (= (duracion tramo1 tramo2) 5)
    (= (duracion tramo2 tramo3) 6)
    (= (duracion tramo2 tramo4) 4)
    (= (duracion tramo3 tramo5) 7)
    (= (duracion tramo4 tramo5) 6)
    (= (duracion tramo2 tramo1) 5)
    (= (duracion tramo3 tramo2) 6)
    (= (duracion tramo4 tramo2) 4)
    (= (duracion tramo5 tramo3) 7)
    (= (duracion tramo5 tramo4) 6)
    (= (costecisterna) 25)
    (= (costepavimentadora) 30)
    (= (costecompactadora) 35)
    (= (coste-total) 0)
)

(:goal (and (at cuadrilla1 tramo1)
            (at cuadrilla2 tramo5)
            (at cuadrilla4 tramo5)
            (at cisterna1 tramo1)
            (at cisterna2 tramo3)
            (at compactadora1 tramo5)
            (compactado tramo1)
            (compactado tramo2)
            (compactado tramo3)
            (compactado tramo4)
            (compactado tramo5)
            (pavimentado tramo1)
            (pavimentado tramo2)
            (pavimentado tramo3)
            (pavimentado tramo4)
            (pavimentado tramo5)
            (aplastado tramo1)
            (aplastado tramo2)
            (aplastado tramo3)
            (aplastado tramo4)
            (aplastado tramo5)
            (pintado tramo1)
            (pintado tramo2)
            (pintado tramo3)
            (pintado tramo4)
            (pintado tramo5)
            (vallado tramo1)
            (vallado tramo2)
            (vallado tramo3)
            (vallado tramo4)
            (vallado tramo5)
            (iluminado tramo3)
            (iluminado tramo4)
            (iluminado tramo5))
)

(:metric minimize (+(*0.2(total-time))(*0.5(coste-total))))
)